-- PostgreSQL translation of the SQLyog tooth-lounge schema.
-- Schema only: patient/account/appointment rows from the dump are intentionally omitted.

create table if not exists public.users (
    user_id bigint generated by default as identity primary key,
    name varchar(100) not null,
    email varchar(255) not null unique,
    password varchar(255) not null,
    role varchar(16) not null default 'patient'
        check (role in ('patient', 'staff')),
    must_change_password boolean not null default false,
    created_at timestamp without time zone null default current_timestamp,
    updated_at timestamp without time zone null default current_timestamp
);

create table if not exists public.patients (
    patient_id bigint generated by default as identity primary key,
    user_id bigint null unique references public.users(user_id) on delete set null on update cascade,
    patient_number varchar(20) not null unique,
    first_name varchar(50) not null,
    last_name varchar(50) not null,
    birth_date date null,
    sex varchar(20) null,
    contact_number varchar(20) null,
    address varchar(255) null,
    created_at timestamp without time zone null default current_timestamp,
    updated_at timestamp without time zone null default current_timestamp
);

create table if not exists public.appointments (
    appointment_id bigint generated by default as identity primary key,
    patient_id bigint not null references public.patients(patient_id) on delete cascade on update cascade,
    preferred_date date not null,
    preferred_start_time time without time zone not null,
    preferred_end_time time without time zone not null,
    confirmed_date date null,
    confirmed_start_time time without time zone null,
    confirmed_end_time time without time zone null,
    reason varchar(255) null,
    status varchar(20) not null default 'pending'
        check (status in ('pending', 'confirmed', 'completed', 'cancelled', 'no_show')),
    created_at timestamp without time zone null default current_timestamp,
    updated_at timestamp without time zone null default current_timestamp
);

create index if not exists fk_appointments_patient on public.appointments(patient_id);

create table if not exists public.visit_records (
    visit_id bigint generated by default as identity primary key,
    patient_id bigint not null references public.patients(patient_id) on delete cascade on update cascade,
    appointment_id bigint not null unique references public.appointments(appointment_id) on delete cascade on update cascade,
    visit_date date not null,
    chief_complaint text null,
    findings text null,
    treatment text null,
    notes text null,
    follow_up text null,
    created_at timestamp without time zone null default current_timestamp,
    updated_at timestamp without time zone null default current_timestamp
);

create index if not exists fk_visit_records_patient on public.visit_records(patient_id);

create table if not exists public.appointment_reminders (
    reminder_id bigint generated by default as identity primary key,
    appointment_id bigint not null,
    reminder_date date not null,
    reminder_type varchar(32) not null,
    created_at timestamp without time zone not null default current_timestamp,
    constraint uq_appointment_reminder unique (appointment_id, reminder_date, reminder_type)
);

create table if not exists public.notifications (
    notification_id bigint generated by default as identity primary key,
    recipient_user_id bigint not null,
    appointment_id bigint null,
    notification_type varchar(40) not null,
    title varchar(160) not null,
    body varchar(500) not null,
    created_at timestamp without time zone not null default current_timestamp,
    read_at timestamp without time zone null
);

create index if not exists idx_notifications_recipient_unread
    on public.notifications(recipient_user_id, read_at, created_at);
create index if not exists idx_notifications_appointment
    on public.notifications(appointment_id);
