<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>@yield('title','The Tooth Lounge') · The Tooth Lounge</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><style>
:root{--teal:#0c5867;--gold:#aa8500;--ink:#263b42;--paper:#f4f8f8}body{background:var(--paper);color:var(--ink);min-height:100vh}.navbar{background:white;border-bottom:1px solid #dce7e9}.navbar-brand img{width:150px;height:52px;object-fit:contain}.navbar .nav-link{color:#425a61;font-weight:500}.navbar .nav-link.active,.navbar .nav-link:hover{color:var(--teal)}.btn-primary{--bs-btn-bg:var(--teal);--bs-btn-border-color:var(--teal);--bs-btn-hover-bg:#084653;--bs-btn-hover-border-color:#084653}.text-brand{color:var(--teal)!important}.page-wrap{max-width:1240px}.card{border:1px solid #e0e9eb;box-shadow:0 3px 16px #163d460b;border-radius:1rem}.card-header{background:#fff;border-bottom-color:#e7eff0}.stat-card{border-left:4px solid var(--teal);height:100%}.stat-value{font-size:2rem;font-weight:700;color:var(--teal)}.form-label{font-weight:600}.badge-pending{background:#fff1c2;color:#765700;border:1px solid #f0d77d}.badge-confirmed{background:#dff3ea;color:#176644}.badge-completed{background:#dceff3;color:#155a69}.badge-cancelled{background:#fbe5e5;color:#9a3030}.badge-no_show{background:#ece8f6;color:#59488b}.calendar-grid{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:3px}.calendar-day{min-height:74px;border:1px solid #dce7e9;background:white;padding:.35rem;border-radius:.35rem;text-decoration:none;color:var(--ink)}.calendar-day:hover{background:#eff8f9}.calendar-day.selected{border:2px solid #008fa3;background:#effafb}.calendar-day.outside{background:#f4f7f8;color:#aab8bc}.calendar-badges{display:flex;flex-wrap:wrap;gap:.2rem;margin-top:.3rem}.calendar-badges .badge{font-size:.59rem;white-space:normal}.footer{color:#71858b}@media(max-width:767px){.calendar-day{min-height:58px;padding:.2rem}.calendar-badges .badge{font-size:.52rem}}@media print{.navbar,.screen-only,.footer{display:none!important}body{background:#fff}.card{box-shadow:none}}
</style></head><body>
<nav class="navbar navbar-expand-xl sticky-top"><div class="container-fluid page-wrap"><a class="navbar-brand" href="{{ auth()->check()?route('dashboard'):route('login') }}"><img src="{{ asset('images/tooth-lounge-logo.png') }}" alt="The Tooth Lounge"></a>
@auth @php($staff=auth()->user()->role==='staff') @php($pendingAttention=$staff?\App\Models\Appointment::where('status','pending')->count():0)
<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nav"><span class="navbar-toggler-icon"></span></button><div class="collapse navbar-collapse" id="nav"><ul class="navbar-nav me-auto">
@if($staff)
<li class="nav-item"><a class="nav-link {{ request()->routeIs('staff.dashboard')?'active':'' }}" href="{{ route('staff.dashboard') }}">Dashboard</a></li><li class="nav-item"><a class="nav-link {{ request()->routeIs('staff.appointments*')?'active':'' }}" href="{{ route('staff.appointments') }}">Appointments @if($pendingAttention)<span class="badge rounded-pill badge-pending">{{ $pendingAttention }}</span>@endif</a></li><li class="nav-item"><a class="nav-link {{ request()->routeIs('staff.patients*')?'active':'' }}" href="{{ route('staff.patients') }}">Patients</a></li><li class="nav-item"><a class="nav-link {{ request()->routeIs('staff.visits*')?'active':'' }}" href="{{ route('staff.visits') }}">Visit records</a></li><li class="nav-item dropdown"><a class="nav-link dropdown-toggle {{ request()->routeIs('staff.reports','staff.activity-log','staff.accounts')?'active':'' }}" data-bs-toggle="dropdown" href="#">More</a><ul class="dropdown-menu"><li><a class="dropdown-item" href="{{ route('staff.reports') }}">Reports</a></li><li><a class="dropdown-item" href="{{ route('staff.activity-log') }}">Activity log</a></li><li><a class="dropdown-item" href="{{ route('staff.accounts') }}">Staff accounts</a></li></ul></li>
@else
<li class="nav-item"><a class="nav-link" href="{{ route('patient.dashboard') }}">Dashboard</a></li><li class="nav-item"><a class="nav-link" href="{{ route('patient.appointments.request') }}">Request appointment</a></li><li class="nav-item"><a class="nav-link" href="{{ route('patient.appointments') }}">Appointments</a></li><li class="nav-item"><a class="nav-link" href="{{ route('patient.visits') }}">Visit history</a></li><li class="nav-item"><a class="nav-link" href="{{ route('patient.profile') }}">Profile</a></li>
@endif</ul><div class="d-flex gap-2 align-items-center pb-2 pb-xl-0"><span class="small text-secondary">{{ auth()->user()->name }}</span><a class="btn btn-sm btn-outline-secondary" href="{{ route('password.change') }}">Password</a><a class="btn btn-sm btn-primary" href="{{ route('logout.confirm') }}">Log out</a></div></div>
@endauth</div></nav><main class="container-fluid page-wrap py-4 py-lg-5">
@if(session('status'))<div class="alert alert-success alert-dismissible fade show">{{ session('status') }}<button class="btn-close" data-bs-dismiss="alert"></button></div>@endif
@if(session('created_patient_credentials'))<div class="alert alert-warning"><strong>Temporary patient credentials (shown once)</strong><br>Email: {{ session('created_patient_credentials.email') }} · Temporary password: {{ session('created_patient_credentials.temporary_password') }} · Patient number: {{ session('created_patient_credentials.patient_number') }}</div>@endif
@if(session('created_staff_credentials'))<div class="alert alert-warning"><strong>Temporary staff credentials (shown once)</strong><br>{{ session('created_staff_credentials.email') }} · {{ session('created_staff_credentials.temporary_password') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><strong>Please review:</strong><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@yield('content')</main><footer class="footer text-center py-4 small">The Tooth Lounge · Clinic appointments and patient records</footer><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script><script src="{{ asset('js/clinic.js') }}" defer></script>@stack('scripts')</body></html>
